import 'package:filmes/models/assets.dart';
import 'package:filmes/models/content.dart';

List<Content> featured = [
  const Content(
    name: 'Stranger Things',
    imageUrl: Assets.strangerThings,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.strangerThingsPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: '13 Reasons Why',
    imageUrl: Assets.thirteenReasonsWhy,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.thirteenReasonsWhyPreview,
    titleImageUrl: Assets.thirteenReasonsWhyTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'The End of the F***ing World',
    imageUrl: Assets.teotfw,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.teotfwPreview,
    titleImageUrl: Assets.teotfwTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'The Crown',
    imageUrl: Assets.crown,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.crownPreview,
    titleImageUrl: Assets.crownTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'Black Mirror',
    imageUrl: Assets.blackMirror,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.blackMirrorPreview,
    titleImageUrl: Assets.blackMirrorTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  )
];
List<Content> popular = [
  const Content(
    name: 'Stranger Things',
    imageUrl: Assets.strangerThings,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.strangerThingsPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'The Witcher',
    imageUrl: Assets.witcher,
    year: 2021,
    seasons: 2,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.witcherPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: '13 Reasons Why',
    imageUrl: Assets.thirteenReasonsWhy,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.thirteenReasonsWhyPreview,
    titleImageUrl: Assets.thirteenReasonsWhyTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'Breaking Bad',
    imageUrl: Assets.breakingBad,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.breakingBadPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'The Umbrella Academy',
    imageUrl: Assets.umbrellaAcademy,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.umbrellaAcademyPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'The End of the F***ing World',
    imageUrl: Assets.teotfw,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.teotfwPreview,
    titleImageUrl: Assets.teotfwTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'The Crown',
    imageUrl: Assets.crown,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.crownPreview,
    titleImageUrl: Assets.crownTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'Black Mirror',
    imageUrl: Assets.blackMirror,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.blackMirrorPreview,
    titleImageUrl: Assets.blackMirrorTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'Dark',
    imageUrl: Assets.dark,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.darkPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'Explained',
    imageUrl: Assets.explained,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.explainedPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
];
List<Content> only = [
  const Content(
    name: 'Stranger Things',
    imageUrl: Assets.strangerThings,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.strangerThingsPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'The Witcher',
    imageUrl: Assets.witcher,
    year: 2021,
    seasons: 2,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.witcherPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: '13 Reasons Why',
    imageUrl: Assets.thirteenReasonsWhy,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.thirteenReasonsWhyPreview,
    titleImageUrl: Assets.thirteenReasonsWhyTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'Breaking Bad',
    imageUrl: Assets.breakingBad,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.breakingBadPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'The Umbrella Academy',
    imageUrl: Assets.umbrellaAcademy,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.umbrellaAcademyPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'The End of the F***ing World',
    imageUrl: Assets.teotfw,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.teotfwPreview,
    titleImageUrl: Assets.teotfwTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'The Crown',
    imageUrl: Assets.crown,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.crownPreview,
    titleImageUrl: Assets.crownTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'Black Mirror',
    imageUrl: Assets.blackMirror,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.blackMirrorPreview,
    titleImageUrl: Assets.blackMirrorTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'Dark',
    imageUrl: Assets.dark,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.darkPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'Explained',
    imageUrl: Assets.explained,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.explainedPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
];
List<Content> trending = [
  const Content(
    name: 'Stranger Things',
    imageUrl: Assets.strangerThings,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.strangerThingsPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'The Witcher',
    imageUrl: Assets.witcher,
    year: 2021,
    seasons: 2,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.witcherPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: '13 Reasons Why',
    imageUrl: Assets.thirteenReasonsWhy,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.thirteenReasonsWhyPreview,
    titleImageUrl: Assets.thirteenReasonsWhyTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'Breaking Bad',
    imageUrl: Assets.breakingBad,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.breakingBadPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'The Umbrella Academy',
    imageUrl: Assets.umbrellaAcademy,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.umbrellaAcademyPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'The End of the F***ing World',
    imageUrl: Assets.teotfw,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.teotfwPreview,
    titleImageUrl: Assets.teotfwTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'The Crown',
    imageUrl: Assets.crown,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.crownPreview,
    titleImageUrl: Assets.crownTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'Black Mirror',
    imageUrl: Assets.blackMirror,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.blackMirrorPreview,
    titleImageUrl: Assets.blackMirrorTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'Dark',
    imageUrl: Assets.dark,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.darkPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'Explained',
    imageUrl: Assets.explained,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.explainedPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
];
List<Content> family = [
  const Content(
    name: 'Stranger Things',
    imageUrl: Assets.strangerThings,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.strangerThingsPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'The Witcher',
    imageUrl: Assets.witcher,
    year: 2021,
    seasons: 2,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.witcherPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: '13 Reasons Why',
    imageUrl: Assets.thirteenReasonsWhy,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.thirteenReasonsWhyPreview,
    titleImageUrl: Assets.thirteenReasonsWhyTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'Breaking Bad',
    imageUrl: Assets.breakingBad,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.breakingBadPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'The Umbrella Academy',
    imageUrl: Assets.umbrellaAcademy,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.umbrellaAcademyPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'The End of the F***ing World',
    imageUrl: Assets.teotfw,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.teotfwPreview,
    titleImageUrl: Assets.teotfwTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'The Crown',
    imageUrl: Assets.crown,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.crownPreview,
    titleImageUrl: Assets.crownTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'Black Mirror',
    imageUrl: Assets.blackMirror,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.blackMirrorPreview,
    titleImageUrl: Assets.blackMirrorTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'Dark',
    imageUrl: Assets.dark,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.darkPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'Explained',
    imageUrl: Assets.explained,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.explainedPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
];
List<Content> released = [
  const Content(
    name: 'Stranger Things',
    imageUrl: Assets.strangerThings,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.strangerThingsPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'The Witcher',
    imageUrl: Assets.witcher,
    year: 2021,
    seasons: 2,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.witcherPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: '13 Reasons Why',
    imageUrl: Assets.thirteenReasonsWhy,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.thirteenReasonsWhyPreview,
    titleImageUrl: Assets.thirteenReasonsWhyTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'Breaking Bad',
    imageUrl: Assets.breakingBad,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.breakingBadPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'The Umbrella Academy',
    imageUrl: Assets.umbrellaAcademy,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.umbrellaAcademyPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'The End of the F***ing World',
    imageUrl: Assets.teotfw,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.teotfwPreview,
    titleImageUrl: Assets.teotfwTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'The Crown',
    imageUrl: Assets.crown,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.crownPreview,
    titleImageUrl: Assets.crownTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'Black Mirror',
    imageUrl: Assets.blackMirror,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.blackMirrorPreview,
    titleImageUrl: Assets.blackMirrorTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'Dark',
    imageUrl: Assets.dark,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.darkPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
  const Content(
    name: 'Explained',
    imageUrl: Assets.explained,
    year: 2022,
    seasons: 4,
    description:
        'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.',
    cast: 'Winona Ryder, David Harbour, Millie Bobby Brown',
    created_by: 'The Duffer Brothers',
    previewUrl: Assets.explainedPreview,
    titleImageUrl: Assets.strangerThingsTitle,
    categories: 'Britânico, Séries de ficção científica, Suspense',
  ),
];

